name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: typescript-bun-app

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure Docker
      run: gcloud auth configure-docker

    - name: Build and Push Docker image
      run: |
        docker build -t gcr.io/$PROJECT_ID/$SERVICE_NAME:${{ github.sha }} .
        docker push gcr.io/$PROJECT_ID/$SERVICE_NAME:${{ github.sha }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy $SERVICE_NAME \
          --image gcr.io/$PROJECT_ID/$SERVICE_NAME:${{ github.sha }} \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated

    - name: Set up Cloud Scheduler
      run: |
        gcloud scheduler jobs create http $SCHEDULER_NAME \
          --schedule "0 0 * * *" \
          --time-zone "UTC" \
          --uri "$SERVICE_URL" \
          --http-method GET \
          --region $REGION \
          --description "Daily run of $SERVICE_NAME" || \
        gcloud scheduler jobs update http $SCHEDULER_NAME \
          --schedule "0 0 * * *" \
          --time-zone "UTC" \
          --uri "$SERVICE_URL" \
          --http-method GET \
          --region $REGION \
          --description "Daily run of $SERVICE_NAME"

    - name: Lint and format check
      run: |
        bun run format